	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_unknown_1::
	.incbin "sound/direct_sound_samples/unknown_01.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_unknown_2::
	.incbin "sound/direct_sound_samples/unknown_02.bin"

	.align 2
DirectSoundWaveData_unknown_3::
	.incbin "sound/direct_sound_samples/unknown_03.bin"

	.align 2
DirectSoundWaveData_unknown_4::
	.incbin "sound/direct_sound_samples/unknown_04.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_unknown_5::
	.incbin "sound/direct_sound_samples/unknown_05.bin"

	.align 2
DirectSoundWaveData_unknown_6::
	.incbin "sound/direct_sound_samples/unknown_06.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_unknown_7::
	.incbin "sound/direct_sound_samples/unknown_07.bin"

	.align 2
DirectSoundWaveData_unknown_8::
	.incbin "sound/direct_sound_samples/unknown_08.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_9::
	.incbin "sound/direct_sound_samples/unknown_09.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_unknown_10::
	.incbin "sound/direct_sound_samples/unknown_10.bin"

	.align 2
DirectSoundWaveData_unknown_11::
	.incbin "sound/direct_sound_samples/unknown_11.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unknown_12::
	.incbin "sound/direct_sound_samples/unknown_12.bin"

	.align 2
DirectSoundWaveData_unknown_13::
	.incbin "sound/direct_sound_samples/unknown_13.bin"

	.align 2
DirectSoundWaveData_unknown_14::
	.incbin "sound/direct_sound_samples/unknown_14.bin"

	.align 2
DirectSoundWaveData_unknown_15::
	.incbin "sound/direct_sound_samples/unknown_15.bin"

	.align 2
DirectSoundWaveData_unknown_16::
	.incbin "sound/direct_sound_samples/unknown_16.bin"

	.align 2
DirectSoundWaveData_unknown_17::
	.incbin "sound/direct_sound_samples/unknown_17.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cries/ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cries/venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cries/charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cries/charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cries/charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cries/squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cries/wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cries/blastoise.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cries/raichu.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cries/vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cries/ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cries/jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cries/wigglytuff.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cries/tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cries/tentacruel.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cries/grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cries/muk.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cries/koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cries/weezing.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cries/tangela.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cries/scyther.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cries/magmar.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cries/ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cries/eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cries/vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cries/jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cries/flareon.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cries/kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cries/kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cries/aerodactyl.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cries/pichu.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cries/igglybuff.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cries/natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cries/xatu.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cries/sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cries/sunflora.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cries/espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cries/umbreon.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cries/scizor.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cries/skarmory.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cries/magby.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cries/ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cries/kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cries/gardevoir.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cries/numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cries/camerupt.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cries/torkoal.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cries/snorunt.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cries/glalie.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cries/regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cries/regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cries/registeel.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cries/latias.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cries/latios.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/kyogre.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/groudon.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/rayquaza.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cries/deoxys.bin"

	.align 2
Cry_Shinx::
	.incbin "sound/direct_sound_samples/cries/shinx.bin"

	.align 2
Cry_Luxio::
	.incbin "sound/direct_sound_samples/cries/luxio.bin"

	.align 2
Cry_Luxray::
	.incbin "sound/direct_sound_samples/cries/luxray.bin"

	.align 2
Cry_Combee::
	.incbin "sound/direct_sound_samples/cries/combee.bin"

	.align 2
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cries/vespiquen.bin"

	.align 2
Cry_Riolu::
	.incbin "sound/direct_sound_samples/cries/riolu.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cries/lucario.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cries/tangrowth.bin"

	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cries/magmortar.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/glaceon.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cries/gallade.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cries/froslass.bin"

	.align 2
Cry_Purrloin::
	.incbin "sound/direct_sound_samples/cries/purrloin.bin"

	.align 2
Cry_Liepard::
	.incbin "sound/direct_sound_samples/cries/liepard.bin"

	.align 2
Cry_Scraggy::
	.incbin "sound/direct_sound_samples/cries/scraggy.bin"

	.align 2
Cry_Scrafty::
	.incbin "sound/direct_sound_samples/cries/scrafty.bin"

	.align 2
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cries/pawniard.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cries/bisharp.bin"

	.align 2
Cry_Deino::
	.incbin "sound/direct_sound_samples/cries/deino.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cries/zweilous.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cries/hydreigon.bin"

	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cries/sylveon.bin"

	.align 2
Cry_Bergmite::
	.incbin "sound/direct_sound_samples/cries/bergmite.bin"

	.align 2
Cry_Avalugg::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Kipvine::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Plaguar::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Photoguar::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Raiad::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Rusalka::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Fallsheer::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Scuiret::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pteroret::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Birrobird::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Eageleag::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Griffogrif::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Mafichu::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Demichu::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Cutbit::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Flabbit::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Blitzrdrix::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Neinsoul::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Spruvyne::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Queryne::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Sampervyne::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Rangife::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Taranalloy::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Alcesteel::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Arakid::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Rakidone::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Totemna::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pskulpt::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Espatch::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Fizzix::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Gravitomix::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Amunatu::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Gropp::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Cyclobber::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Totsicle::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Frostidon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Glacriek::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Ameoerg::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Sarphon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Aerophagus::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Roxxik::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Gravelisk::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Skarmoros::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Phenyxy::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Resuraketh::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Torkyllium::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Minotrant::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Zigglygruf::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Gomm::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Mountegrom::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Ovarapt::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Velokota::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Utabazai::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Kroa::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Kroaea::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Kroaeakaoa::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Archigloom::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Nemelt::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Varaflare::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Komodor::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Silhou::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Silgaunt::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Vaileye::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Bloodnaunt::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Anphage::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Tusgoyf::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Llurscayf::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Cranisect::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Skultulant::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Chrysal::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Vellavale::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Vellidaxos::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Ghoulslash::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Murkeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Obsideon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Fureon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Sootheon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Mooreon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Frosteon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Radeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pospheon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Pulseon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Staticeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Blizzeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Dynameon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Devileon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Cindereon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Blaneon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Eclipseon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Aromeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Isycleon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Zereon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Noctiveon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pineon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pixeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Lunneon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Cherreon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Hazeon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Sereneon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Misteon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pureon::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Salatad::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Salanip::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Salaslam::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Halmstar::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Snuffuzz::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Stickit::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Stickut::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Ugling::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Swellegant::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Angling::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Angelish::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Angelight::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Aquad::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Smaqua::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Beopup::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Werehide::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Vambat::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Dracubat::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Countula::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pupool::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Pooldog::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Porfin::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Doflap::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Paradiso::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Parasea::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Aqlarva::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Mosliquo::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Nawale::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Whaley::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Squidart::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Lisquid::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Cry_Hamawl::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

.align 2
Silvicious::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"


	.align 2
Cry_VenusaurMega::
	.incbin "sound/direct_sound_samples/cries/mega_venusaur.bin"

	.align 2
Cry_CharizardMegaX::
	.incbin "sound/direct_sound_samples/cries/mega_charizard_x.bin"

	.align 2
Cry_CharizardMegaY::
	.incbin "sound/direct_sound_samples/cries/mega_charizard_y.bin"

	.align 2
Cry_BlastoiseMega::
	.incbin "sound/direct_sound_samples/cries/mega_blastoise.bin"

	.align 2
Cry_ScizorMega::
	.incbin "sound/direct_sound_samples/cries/mega_scizor.bin"

	.align 2
Cry_GardevoirMega::
	.incbin "sound/direct_sound_samples/cries/mega_gardevoir.bin"

	.align 2
Cry_CameruptMega::
	.incbin "sound/direct_sound_samples/cries/mega_camerupt.bin"

	.align 2
Cry_GlalieMega::
	.incbin "sound/direct_sound_samples/cries/mega_glalie.bin"

	.align 2
Cry_LucarioMega::
	.incbin "sound/direct_sound_samples/cries/mega_lucario.bin"

	.align 2
Cry_GalladeMega::
	.incbin "sound/direct_sound_samples/cries/mega_gallade.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_unknown_18::
	.incbin "sound/direct_sound_samples/unknown_18.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_Phoneme_1::
	.incbin "sound/direct_sound_samples/phonemes/01.bin"

	.align 2
DirectSoundWaveData_Phoneme_2::
	.incbin "sound/direct_sound_samples/phonemes/02.bin"

	.align 2
DirectSoundWaveData_Phoneme_3::
	.incbin "sound/direct_sound_samples/phonemes/03.bin"

	.align 2
DirectSoundWaveData_Phoneme_4::
	.incbin "sound/direct_sound_samples/phonemes/04.bin"

	.align 2
DirectSoundWaveData_Phoneme_5::
	.incbin "sound/direct_sound_samples/phonemes/05.bin"

	.align 2
DirectSoundWaveData_Phoneme_6::
	.incbin "sound/direct_sound_samples/phonemes/06.bin"

	.align 2
DirectSoundWaveData_Phoneme_7::
	.incbin "sound/direct_sound_samples/phonemes/07.bin"

	.align 2
DirectSoundWaveData_Phoneme_8::
	.incbin "sound/direct_sound_samples/phonemes/08.bin"

	.align 2
DirectSoundWaveData_Phoneme_9::
	.incbin "sound/direct_sound_samples/phonemes/09.bin"

	.align 2
DirectSoundWaveData_Phoneme_10::
	.incbin "sound/direct_sound_samples/phonemes/10.bin"

	.align 2
DirectSoundWaveData_Phoneme_11::
	.incbin "sound/direct_sound_samples/phonemes/11.bin"

	.align 2
DirectSoundWaveData_Phoneme_12::
	.incbin "sound/direct_sound_samples/phonemes/12.bin"

	.align 2
DirectSoundWaveData_Phoneme_13::
	.incbin "sound/direct_sound_samples/phonemes/13.bin"

	.align 2
DirectSoundWaveData_Phoneme_14::
	.incbin "sound/direct_sound_samples/phonemes/14.bin"

	.align 2
DirectSoundWaveData_Phoneme_15::
	.incbin "sound/direct_sound_samples/phonemes/15.bin"

	.align 2
DirectSoundWaveData_Phoneme_16::
	.incbin "sound/direct_sound_samples/phonemes/16.bin"

	.align 2
DirectSoundWaveData_Phoneme_17::
	.incbin "sound/direct_sound_samples/phonemes/17.bin"

	.align 2
DirectSoundWaveData_Phoneme_18::
	.incbin "sound/direct_sound_samples/phonemes/18.bin"

	.align 2
DirectSoundWaveData_Phoneme_19::
	.incbin "sound/direct_sound_samples/phonemes/19.bin"

	.align 2
DirectSoundWaveData_Phoneme_20::
	.incbin "sound/direct_sound_samples/phonemes/20.bin"

	.align 2
DirectSoundWaveData_Phoneme_21::
	.incbin "sound/direct_sound_samples/phonemes/21.bin"

	.align 2
DirectSoundWaveData_Phoneme_22::
	.incbin "sound/direct_sound_samples/phonemes/22.bin"

	.align 2
DirectSoundWaveData_Phoneme_23::
	.incbin "sound/direct_sound_samples/phonemes/23.bin"

	.align 2
DirectSoundWaveData_Phoneme_24::
	.incbin "sound/direct_sound_samples/phonemes/24.bin"

	.align 2
DirectSoundWaveData_Phoneme_25::
	.incbin "sound/direct_sound_samples/phonemes/25.bin"

	.align 2
DirectSoundWaveData_Phoneme_26::
	.incbin "sound/direct_sound_samples/phonemes/26.bin"

	.align 2
DirectSoundWaveData_Phoneme_27::
	.incbin "sound/direct_sound_samples/phonemes/27.bin"

	.align 2
DirectSoundWaveData_Phoneme_28::
	.incbin "sound/direct_sound_samples/phonemes/28.bin"

	.align 2
DirectSoundWaveData_Phoneme_29::
	.incbin "sound/direct_sound_samples/phonemes/29.bin"

	.align 2
DirectSoundWaveData_Phoneme_30::
	.incbin "sound/direct_sound_samples/phonemes/30.bin"

	.align 2
DirectSoundWaveData_Phoneme_31::
	.incbin "sound/direct_sound_samples/phonemes/31.bin"

	.align 2
DirectSoundWaveData_Phoneme_32::
	.incbin "sound/direct_sound_samples/phonemes/32.bin"

	.align 2
DirectSoundWaveData_Phoneme_33::
	.incbin "sound/direct_sound_samples/phonemes/33.bin"

	.align 2
DirectSoundWaveData_Phoneme_34::
	.incbin "sound/direct_sound_samples/phonemes/34.bin"

	.align 2
DirectSoundWaveData_Phoneme_35::
	.incbin "sound/direct_sound_samples/phonemes/35.bin"

	.align 2
DirectSoundWaveData_Phoneme_36::
	.incbin "sound/direct_sound_samples/phonemes/36.bin"

	.align 2
DirectSoundWaveData_Phoneme_37::
	.incbin "sound/direct_sound_samples/phonemes/37.bin"

	.align 2
DirectSoundWaveData_Phoneme_38::
	.incbin "sound/direct_sound_samples/phonemes/38.bin"

	.align 2
DirectSoundWaveData_Phoneme_39::
	.incbin "sound/direct_sound_samples/phonemes/39.bin"

	.align 2
DirectSoundWaveData_Phoneme_40::
	.incbin "sound/direct_sound_samples/phonemes/40.bin"

	.align 2
DirectSoundWaveData_Phoneme_41::
	.incbin "sound/direct_sound_samples/phonemes/41.bin"

	.align 2
DirectSoundWaveData_Phoneme_42::
	.incbin "sound/direct_sound_samples/phonemes/42.bin"

	.align 2
DirectSoundWaveData_Phoneme_43::
	.incbin "sound/direct_sound_samples/phonemes/43.bin"

	.align 2
DirectSoundWaveData_Phoneme_44::
	.incbin "sound/direct_sound_samples/phonemes/44.bin"

	.align 2
DirectSoundWaveData_Phoneme_45::
	.incbin "sound/direct_sound_samples/phonemes/45.bin"

	.align 2
DirectSoundWaveData_Phoneme_46::
	.incbin "sound/direct_sound_samples/phonemes/46.bin"

	.align 2
DirectSoundWaveData_Phoneme_47::
	.incbin "sound/direct_sound_samples/phonemes/47.bin"

	.align 2
DirectSoundWaveData_Phoneme_48::
	.incbin "sound/direct_sound_samples/phonemes/48.bin"

	.align 2
DirectSoundWaveData_Phoneme_49::
	.incbin "sound/direct_sound_samples/phonemes/49.bin"

	.align 2
DirectSoundWaveData_Phoneme_50::
	.incbin "sound/direct_sound_samples/phonemes/50.bin"

	.align 2
DirectSoundWaveData_Phoneme_51::
	.incbin "sound/direct_sound_samples/phonemes/51.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
